version: "3.7"

services:
  app:
    container_name: go_consumer
    build: ./
    volumes:
      - ./cmd:/app
    networks:
      - go_api_network

networks:
  go_api_network:
    driver: bridge
    external: true